# Generated by Django 5.0.6 on 2024-05-23 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmosphere_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('like', models.BooleanField(verbose_name=True)),
                ('dislike', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
