# Generated by Django 4.1.13 on 2024-05-28 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appmosphere_app', '0003_feed_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilepage',
            name='comment',
            field=models.ManyToManyField(to='appmosphere_app.comment'),
        ),
        migrations.AlterField(
            model_name='feed',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appmosphere_app.user'),
        ),
    ]
